# Generated by Django 5.0.2 on 2024-03-01 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_code', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Создано'), ('SHIPPED', 'Отправлено'), ('IN_TRANSIT', 'В пути'), ('DELIVERED', 'Доставлено'), ('RECEIVED', 'Получено клиентом'), ('DONE', 'Принято клиентом')], default='PENDING', max_length=20)),
                ('in_archive', models.BooleanField(choices=[(False, 'Не в архиве'), (True, 'В архиве')], default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
